site_name: lernOS - Keep Calm and Learn On
site_url: https://lernos.org/en
docs_dir: src
site_dir: ../docs/en

nav:
    - Home: index.md
    - About lernOS: 0-about.md
    - Guidelines:
      - Overview: 1-guides.md
      - Artificial Intelligence: guides/ai.md
    - Learning in Circles: 2-learning-circle.md
    - Publications: 4-publications.md
    - Blog: 6-blog.md
    - FAQ: 5-faq.md
    - Links:
      - lernOS Presentation: https://lernos.org/de-slides
      - lernOS Quick-Start Guide: lernOS-Quick-Start-Guide-de-v03.pdf
      - lernOS Glossary: lernos-glossary.md
      - CONNECT Community: https://community.cogneon.de
      - Meetup Group: https://www.meetup.com/de-DE/lernos-connect/
      - Peerfinder: https://web.peerfinder.app
    - Support: 3-support.md
theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
        scheme: lernos
    language: en
    icon:
      repo: fontawesome/brands/github
      logo: material/home

extra_css:
  - stylesheets/extra.css

repo_name: 'cogneon/lernos'
repo_url: 'https://github.com/cogneon/lernos'

extra:
    social:
        - icon: fontawesome/brands/mastodon
          link: 'https://colearn.social/@lernos'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    giscus: true
    alternate:
      - name: German
        link: https://lernos.org/de
        lang: de
    generator: false

copyright: cogneon.de/impressum

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html

plugins:
  - search